package com.azercell.marketplace.common.domain;

public enum ErrorCode {

    // product
    PRODUCT_NAME_REQUIRED,
    PRODUCT_SKU_REQUIRED,
    PRODUCT_SKU_ALREADY_EXISTS,
    PRODUCT_NOT_FOUND,
    PRODUCT_BASE_PRICE_INVALID,
    PRODUCT_VARIANT_DUPLICATE,
    PRODUCT_CREDIT_PLAN_REQUIRED,


    // variant
    VARIANT_COLOR_REQUIRED,
    VARIANT_SKU_REQUIRED,
    PRODUCT_VARIANT_REQUIRED,

    // product variant image
    PRODUCT_VARIANT_IMAGE,
    PRODUCT_VARIANT_IMAGE_DUPLICATE,
    PRODUCT_IMAGE_URL_REQUIRED,

    // color
    COLOR_NAME_REQUIRED,
    COLOR_HEX_INVALID,

    // brand
    BRAND_NAME_REQUIRED,
    BRAND_CODE_INVALID,
    BRAND_ID_REQUIRED,
    BRAND_CODE_REQUIRED,
    BRAND_NOT_FOUND,
    BRAND_NAME_ALREADY_EXISTS,
    BRAND_CODE_ALREADY_EXISTS,

    // category
    CATEGORY_NAME_REQUIRED,
    CATEGORY_NOT_FOUND,
    CATEGORY_CIRCULAR_REFERENCE,

    // credit
    CREDIT_PLAN_NOT_FOUND,
    CREDIT_PLAN_NOT_ACTIVE,
    CREDIT_PLAN_NAME_REQUIRED,
    CREDIT_PLAN_MONTHS_INVALID,
    CREDIT_PLAN_RATE_INVALID,
    ORDER_CREDIT_NOT_ACTIVE,
    ORDER_CREDIT_NOT_FOUND,
    ORDER_CREDIT_ALREADY_EXISTS,
    INSTALLMENT_ALREADY_PAID,
    INSTALLMENT_NOT_FOUND,

    // warehouse (stocks)
    WAREHOUSE_NOT_FOUND,
    WAREHOUSE_NAME_REQUIRED,
    WAREHOUSE_CODE_REQUIRED,
    WAREHOUSE_CODE_INVALID,
    WAREHOUSE_CODE_ALREADY_EXISTS,

    // inventory
    INVENTORY_NOT_FOUND,
    INVENTORY_QUANTITY_INVALID,
    INVENTORY_INSUFFICIENT_STOCK,

    // orders
    ORDER_NOT_FOUND,
    ORDER_EMPTY,
    ORDER_ITEM_QUANTITY_INVALID,
    ORDER_VARIANT_NOT_FOUND,
    ORDER_INVALID_STATUS_TRANSITION,
    ORDER_NO_FULFILMENT_WAREHOUSE,

    // users
    USER_NOT_FOUND,

    // general
    ENTITY_NOT_FOUND,
    INVALID_ARGUMENT,
}